In [139]:

import pandas as pd
import numpy as np

In [140]:
dataset=pd.read_csv(r"D:\Datasets\AirQualityUCI.csv")
dataset

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0     10-03-2004  18:00:00     2.6       1360.0     150.0      11.9   
1     10-03-2004  19:00:00     2.0       1292.0     112.0       9.4   
2     10-03-2004  20:00:00     2.2       1402.0      88.0       9.0   
3     10-03-2004  21:00:00     2.2       1376.0      80.0       9.2   
4     10-03-2004  22:00:00     1.6       1272.0      51.0       6.5   
...          ...       ...     ...          ...       ...       ...   
9466         NaN       NaN     NaN          NaN       NaN       NaN   
9467         NaN       NaN     NaN          NaN       NaN       NaN   
9468         NaN       NaN     NaN          NaN       NaN       NaN   
9469         NaN       NaN     NaN          NaN       NaN       NaN   
9470         NaN       NaN     NaN          NaN       NaN       NaN   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0            1046.0    166.0        1056.0    113.0        1692.0   
1             955.0    103.0        1174.0     92.0        1559.0   
2             939.0    131.0        1140.0    114.0        1555.0   
3             948.0    172.0        1092.0    122.0        1584.0   
4             836.0    131.0        1205.0    116.0        1490.0   
...             ...      ...           ...      ...           ...   
9466            NaN      NaN           NaN      NaN           NaN   
9467            NaN      NaN           NaN      NaN           NaN   
9468            NaN      NaN           NaN      NaN           NaN   
9469            NaN      NaN           NaN      NaN           NaN   
9470            NaN      NaN           NaN      NaN           NaN   

      PT08.S5(O3)     T    RH      AH  Unnamed: 15  Unnamed: 16  
0          1268.0  13.6  48.9  0.7578          NaN          NaN  
1           972.0  13.3  47.7  0.7255          NaN          NaN  
2          1074.0  11.9  54.0  0.7502          NaN          NaN  
3          1203.0  11.0  60.0  0.7867          NaN          NaN  
4          1110.0  11.2  59.6  0.7888          NaN          NaN  
...           ...   ...   ...     ...          ...          ...  
9466          NaN   NaN   NaN     NaN          NaN          NaN  
9467          NaN   NaN   NaN     NaN          NaN          NaN  
9468          NaN   NaN   NaN     NaN          NaN          NaN  
9469          NaN   NaN   NaN     NaN          NaN          NaN  
9470          NaN   NaN   NaN     NaN          NaN          NaN  

[9471 rows x 17 columns]

In [141]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           9357 non-null   object 
 1   Time           9357 non-null   object 
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
 15  Unnamed: 15    0 non-null      float64
 16  Unnamed: 16    0 non-null      float64
dtypes: float64(15), object(2)
memory usage: 1.2+ MB


In [142]:
dataset.isnull().any()

Date             True
Time             True
CO(GT)           True
PT08.S1(CO)      True
NMHC(GT)         True
C6H6(GT)         True
PT08.S2(NMHC)    True
NOx(GT)          True
PT08.S3(NOx)     True
NO2(GT)          True
PT08.S4(NO2)     True
PT08.S5(O3)      True
T                True
RH               True
AH               True
Unnamed: 15      True
Unnamed: 16      True
dtype: bool

In [143]:
fn=dataset["CO(GT)"].max()
fn

11.9

In [144]:
a=dataset["CO(GT)"].fillna(fn,inplace=True)
a

In [145]:
dataset.isnull().any()

Date              True
Time              True
CO(GT)           False
PT08.S1(CO)       True
NMHC(GT)          True
C6H6(GT)          True
PT08.S2(NMHC)     True
NOx(GT)           True
PT08.S3(NOx)      True
NO2(GT)           True
PT08.S4(NO2)      True
PT08.S5(O3)       True
T                 True
RH                True
AH                True
Unnamed: 15       True
Unnamed: 16       True
dtype: bool

In [146]:
fn=dataset["PT08.S1(CO)"].max()
fn

2040.0

In [147]:
b=dataset["PT08.S1(CO)"].fillna(fn,inplace=True)
b

In [148]:
dataset.isnull().any()

Date              True
Time              True
CO(GT)           False
PT08.S1(CO)      False
NMHC(GT)          True
C6H6(GT)          True
PT08.S2(NMHC)     True
NOx(GT)           True
PT08.S3(NOx)      True
NO2(GT)           True
PT08.S4(NO2)      True
PT08.S5(O3)       True
T                 True
RH                True
AH                True
Unnamed: 15       True
Unnamed: 16       True
dtype: bool

In [149]:
fn=dataset["NMHC(GT)"].max()
fn

1189.0

In [150]:
c=dataset["NMHC(GT)"].fillna(fn,inplace=True)
c

In [151]:
dataset.isnull().any()

Date              True
Time              True
CO(GT)           False
PT08.S1(CO)      False
NMHC(GT)         False
C6H6(GT)          True
PT08.S2(NMHC)     True
NOx(GT)           True
PT08.S3(NOx)      True
NO2(GT)           True
PT08.S4(NO2)      True
PT08.S5(O3)       True
T                 True
RH                True
AH                True
Unnamed: 15       True
Unnamed: 16       True
dtype: bool

In [152]:
fn=dataset["C6H6(GT)"].max()
fn

63.7

In [153]:
d=dataset["C6H6(GT)"].fillna(fn,inplace=True)
d

In [154]:
dataset.isnull().any()

Date              True
Time              True
CO(GT)           False
PT08.S1(CO)      False
NMHC(GT)         False
C6H6(GT)         False
PT08.S2(NMHC)     True
NOx(GT)           True
PT08.S3(NOx)      True
NO2(GT)           True
PT08.S4(NO2)      True
PT08.S5(O3)       True
T                 True
RH                True
AH                True
Unnamed: 15       True
Unnamed: 16       True
dtype: bool

In [155]:
fn=dataset["PT08.S2(NMHC)"].max()
fn

2214.0

In [156]:
d=dataset["PT08.S2(NMHC)"].fillna(fn,inplace=True)
d

In [157]:
dataset.isnull().any()

Date              True
Time              True
CO(GT)           False
PT08.S1(CO)      False
NMHC(GT)         False
C6H6(GT)         False
PT08.S2(NMHC)    False
NOx(GT)           True
PT08.S3(NOx)      True
NO2(GT)           True
PT08.S4(NO2)      True
PT08.S5(O3)       True
T                 True
RH                True
AH                True
Unnamed: 15       True
Unnamed: 16       True
dtype: bool

In [158]:
fn=dataset["AH"].max()
fn

2.231

In [159]:
e=dataset["AH"].fillna(fn,inplace=True)
e

In [160]:
dataset.isnull().any()

Date              True
Time              True
CO(GT)           False
PT08.S1(CO)      False
NMHC(GT)         False
C6H6(GT)         False
PT08.S2(NMHC)    False
NOx(GT)           True
PT08.S3(NOx)      True
NO2(GT)           True
PT08.S4(NO2)      True
PT08.S5(O3)       True
T                 True
RH                True
AH               False
Unnamed: 15       True
Unnamed: 16       True
dtype: bool

In [161]:
data=dataset[["CO(GT)","PT08.S1(CO)","NMHC(GT)","C6H6(GT)","PT08.S2(NMHC)","AH"]]
data

CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  PT08.S2(NMHC)      AH
0        2.6       1360.0     150.0      11.9         1046.0  0.7578
1        2.0       1292.0     112.0       9.4          955.0  0.7255
2        2.2       1402.0      88.0       9.0          939.0  0.7502
3        2.2       1376.0      80.0       9.2          948.0  0.7867
4        1.6       1272.0      51.0       6.5          836.0  0.7888
...      ...          ...       ...       ...            ...     ...
9466    11.9       2040.0    1189.0      63.7         2214.0  2.2310
9467    11.9       2040.0    1189.0      63.7         2214.0  2.2310
9468    11.9       2040.0    1189.0      63.7         2214.0  2.2310
9469    11.9       2040.0    1189.0      63.7         2214.0  2.2310
9470    11.9       2040.0    1189.0      63.7         2214.0  2.2310

[9471 rows x 6 columns]

In [170]:
x=data.iloc[0:5000,[0,1,2,3,4]]
x

CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  PT08.S2(NMHC)
0        2.6       1360.0     150.0      11.9         1046.0
1        2.0       1292.0     112.0       9.4          955.0
2        2.2       1402.0      88.0       9.0          939.0
3        2.2       1376.0      80.0       9.2          948.0
4        1.6       1272.0      51.0       6.5          836.0
...      ...          ...       ...       ...            ...
4995  -200.0       1084.0    -200.0      10.0          979.0
4996  -200.0       1039.0    -200.0       8.9          936.0
4997  -200.0       1011.0    -200.0       7.4          875.0
4998  -200.0        968.0    -200.0       6.4          831.0
4999  -200.0        867.0    -200.0       3.7          693.0

[5000 rows x 5 columns]

In [163]:
x.shape

(5000, 5)

In [171]:
y=data.iloc[0:5000,-1]
y

0       0.7578
1       0.7255
2       0.7502
3       0.7867
4       0.7888
         ...  
4995    1.4899
4996    1.4787
4997    1.4642
4998    1.4592
4999    1.4383
Name: AH, Length: 5000, dtype: float64

In [165]:
y.shape

(5000,)

In [166]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [172]:
x_train

array([[ 2.500e+00,  1.277e+03,  2.030e+02,  9.300e+00,  9.520e+02],
       [-2.000e+02,  1.154e+03, -2.000e+02,  8.500e+00,  9.190e+02],
       [ 1.400e+00,  9.230e+02, -2.000e+02,  6.000e+00,  8.110e+02],
       ...,
       [ 2.200e+00,  1.053e+03, -2.000e+02,  1.310e+01,  1.087e+03],
       [ 1.500e+00,  9.630e+02, -2.000e+02,  7.400e+00,  8.720e+02],
       [ 1.000e+00,  8.570e+02, -2.000e+02,  5.100e+00,  7.690e+02]])

In [177]:
x_test

array([[ 3.000e+00,  1.307e+03, -2.000e+02,  1.910e+01,  1.270e+03],
       [ 1.300e+00,  1.029e+03, -2.000e+02,  8.100e+00,  9.040e+02],
       [ 6.000e-01,  8.650e+02, -2.000e+02,  5.100e+00,  7.670e+02],
       ...,
       [-2.000e+02,  8.750e+02, -2.000e+02,  3.000e+00,  6.540e+02],
       [ 1.500e+00,  9.430e+02,  1.320e+02,  6.800e+00,  8.500e+02],
       [-2.000e+02,  1.003e+03, -2.000e+02,  6.800e+00,  8.490e+02]])

In [174]:
y_train

array([0.9928, 1.0722, 1.3116, ..., 1.1279, 1.7546, 0.9362])

In [175]:
y_test

array([   2.019 ,    1.4502,    0.8499,    1.7141,    1.0142,    1.253 ,
          0.862 ,    1.1021,    0.7584,    0.9966,    1.3467,    1.1842,
          0.8728,    1.1787,    0.9848,    0.8057,    1.0613,    1.5484,
          0.9497,    1.2817,    0.6233,    0.7598,    1.3552,    0.6481,
          1.6917,    0.8807,    1.1509,    0.9631,    1.0669,    0.9147,
          1.2234,    1.039 ,    1.2501,    2.0202,    0.7213,    1.0772,
          0.9101,    0.8467,    1.3874,    0.8921,    2.0492,    1.2233,
          0.9799,    1.2884,    0.7624,    1.6668,    1.1462,    1.9018,
          0.9008,    0.8219,    1.0086,    1.5877,    1.8381,    0.9634,
          0.8331,    0.9939,    2.1164,    1.358 ,    1.5722,    0.9461,
       -200.    ,    0.7532,    1.2642,    0.908 ,    1.1838,    1.4653,
          0.7771,    1.0748,    0.8956,    1.0149,    0.8929,    1.0865,
          0.9599,    1.6491,    0.9224,    1.1109,    1.6265,    0.8242,
          1.0249,    0.8273,    1.4913,    1.1353, 

In [167]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()
l1.fit(x_train,y_train)

LinearRegression()

In [168]:
y_pred=l1.predict(x_test)
y_pred

array([ 1.66641507e+00,  3.69667899e-01,  1.09102037e+00,  4.31597410e-01,
        2.47799253e+00,  5.10784466e-01,  1.68928759e+00,  2.29024154e+00,
       -4.89559366e-01,  5.64059732e-01,  2.13913815e+00,  2.14632337e+00,
       -5.97751898e-02,  1.07184968e+00,  8.59315464e-01,  5.72936259e-01,
        1.67302643e+00,  8.25916282e-01,  1.58956372e+00,  4.86894061e-01,
        4.24578685e+00, -4.17580930e-01,  2.17811226e+00,  6.11848879e-01,
        1.85336101e+00,  8.73276107e-01,  2.61017173e-01,  1.56880560e+00,
        1.57233763e-01,  9.88626435e-02,  2.30889703e+00, -2.53674049e-01,
        4.16080614e-01,  4.95261307e-01, -2.93563691e-01,  3.95131072e-01,
       -3.64374390e-01,  3.30386637e+00,  2.08850372e-01,  6.15242947e-01,
        3.57011566e-01,  5.72889800e-01,  2.23054220e+00,  9.46617258e-02,
        3.59126208e+00,  1.33143587e+00,  3.21197738e-01,  1.02418531e+00,
        1.65468103e+00,  5.22544829e-01,  8.17471662e+00,  1.90977020e+00,
        6.14561597e-01,  

In [178]:
y_test

array([   2.019 ,    1.4502,    0.8499,    1.7141,    1.0142,    1.253 ,
          0.862 ,    1.1021,    0.7584,    0.9966,    1.3467,    1.1842,
          0.8728,    1.1787,    0.9848,    0.8057,    1.0613,    1.5484,
          0.9497,    1.2817,    0.6233,    0.7598,    1.3552,    0.6481,
          1.6917,    0.8807,    1.1509,    0.9631,    1.0669,    0.9147,
          1.2234,    1.039 ,    1.2501,    2.0202,    0.7213,    1.0772,
          0.9101,    0.8467,    1.3874,    0.8921,    2.0492,    1.2233,
          0.9799,    1.2884,    0.7624,    1.6668,    1.1462,    1.9018,
          0.9008,    0.8219,    1.0086,    1.5877,    1.8381,    0.9634,
          0.8331,    0.9939,    2.1164,    1.358 ,    1.5722,    0.9461,
       -200.    ,    0.7532,    1.2642,    0.908 ,    1.1838,    1.4653,
          0.7771,    1.0748,    0.8956,    1.0149,    0.8929,    1.0865,
          0.9599,    1.6491,    0.9224,    1.1109,    1.6265,    0.8242,
          1.0249,    0.8273,    1.4913,    1.1353, 