In [5]:
import numpy as np
import pandas as pd

In [7]:
dataset=pd.read_csv("D:\Datasets\HousePrice.csv")
dataset

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK    SQUARE_FT  \
0         Owner                 0.0     0        2       BHK  1300.236407   
1           NaN                 0.0     0        2       BHK  1275.000000   
2         Owner                 NaN     0        2       BHK   933.159722   
3           NaN                 0.0     1        2       BHK   929.921143   
4        Dealer                 1.0     0        2       BHK   999.009247   
...         ...                 ...   ...      ...       ...          ...   
29446     Owner                 0.0     0        3       BHK  2500.000000   
29447     Owner                 0.0     0        2       BHK   769.230769   
29448    Dealer                 0.0     0        2       BHK  1022.641509   
29449     Owner                 0.0     0        2       BHK   927.079009   
29450    Dealer                 0.0     1        2       BHK   896.774194   

       READY_TO_MOVE  RESALE                            ADDRESS  LONGITUDE  \
0                  1       1              Ksfc Layout,Bangalore  12.969910   
1                  1       1          Vishweshwara Nagar,Mysore  12.274538   
2                  1       1                   Jigani,Bangalore  12.778033   
3                  1       1        Sector-1 Vaishali,Ghaziabad  28.642300   
4                  0       1                   New Town,Kolkata  22.592200   
...              ...     ...                                ...        ...   
29446              1       1               Shamshabad Road,Agra  27.140626   
29447              1       1  E3-108, Lake View Recidency,,Vapi  39.945409   
29448              1       1                  Ajmer Road,Jaipur  26.928785   
29449              1       1             Sholinganallur,Chennai  12.900150   
29450              1       1                   Jagatpura,Jaipur  26.832353   

        LATITUDE  TARGET(PRICE_IN_LACS)  
0      77.597960                   55.0  
1      76.644605                   51.0  
2      77.632191                    NaN  
3      77.344500                   62.5  
4      88.484911                   60.5  
...          ...                    ...  
29446  78.043277                   45.0  
29447 -86.150721                   16.0  
29448  75.828002                   27.1  
29449  80.227910                   67.0  
29450  75.841749                   27.8  

[29451 rows x 12 columns]

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   POSTED_BY              29449 non-null  object 
 1   UNDER_CONSTRUCTION     29450 non-null  float64
 2   RERA                   29451 non-null  int64  
 3   BHK_NO.                29451 non-null  int64  
 4   BHK_OR_RK              29451 non-null  object 
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64  
 7   RESALE                 29451 non-null  int64  
 8   ADDRESS                29451 non-null  object 
 9   LONGITUDE              29451 non-null  float64
 10  LATITUDE               29451 non-null  float64
 11  TARGET(PRICE_IN_LACS)  29447 non-null  float64
dtypes: float64(5), int64(4), object(3)
memory usage: 2.7+ MB


In [9]:
dataset.isnull().any()

POSTED_BY                 True
UNDER_CONSTRUCTION        True
RERA                     False
BHK_NO.                  False
BHK_OR_RK                False
SQUARE_FT                False
READY_TO_MOVE            False
RESALE                   False
ADDRESS                  False
LONGITUDE                False
LATITUDE                 False
TARGET(PRICE_IN_LACS)     True
dtype: bool

In [11]:
fn=dataset["UNDER_CONSTRUCTION"].mean()
fn

0.1797623089983022

In [13]:
a=dataset["UNDER_CONSTRUCTION"].fillna(fn,inplace=True)
a

In [28]:
fn=dataset["TARGET(PRICE_IN_LACS)"].mean()
fn

142.91124596732996

In [29]:
b=dataset["TARGET(PRICE_IN_LACS)"].fillna(fn,inplace=True)
b

In [30]:
dataset.isnull().any()

POSTED_BY                 True
UNDER_CONSTRUCTION       False
RERA                     False
BHK_NO.                  False
BHK_OR_RK                False
SQUARE_FT                False
READY_TO_MOVE            False
RESALE                   False
ADDRESS                  False
LONGITUDE                False
LATITUDE                 False
TARGET(PRICE_IN_LACS)    False
dtype: bool

In [31]:
dataset

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK    SQUARE_FT  \
0         Owner            0.000000     0        2       BHK  1300.236407   
1           NaN            0.000000     0        2       BHK  1275.000000   
2         Owner            0.179762     0        2       BHK   933.159722   
3           NaN            0.000000     1        2       BHK   929.921143   
4        Dealer            1.000000     0        2       BHK   999.009247   
...         ...                 ...   ...      ...       ...          ...   
29446     Owner            0.000000     0        3       BHK  2500.000000   
29447     Owner            0.000000     0        2       BHK   769.230769   
29448    Dealer            0.000000     0        2       BHK  1022.641509   
29449     Owner            0.000000     0        2       BHK   927.079009   
29450    Dealer            0.000000     1        2       BHK   896.774194   

       READY_TO_MOVE  RESALE                            ADDRESS  LONGITUDE  \
0                  1       1              Ksfc Layout,Bangalore  12.969910   
1                  1       1          Vishweshwara Nagar,Mysore  12.274538   
2                  1       1                   Jigani,Bangalore  12.778033   
3                  1       1        Sector-1 Vaishali,Ghaziabad  28.642300   
4                  0       1                   New Town,Kolkata  22.592200   
...              ...     ...                                ...        ...   
29446              1       1               Shamshabad Road,Agra  27.140626   
29447              1       1  E3-108, Lake View Recidency,,Vapi  39.945409   
29448              1       1                  Ajmer Road,Jaipur  26.928785   
29449              1       1             Sholinganallur,Chennai  12.900150   
29450              1       1                   Jagatpura,Jaipur  26.832353   

        LATITUDE  TARGET(PRICE_IN_LACS)  
0      77.597960              55.000000  
1      76.644605              51.000000  
2      77.632191             142.911246  
3      77.344500              62.500000  
4      88.484911              60.500000  
...          ...                    ...  
29446  78.043277              45.000000  
29447 -86.150721              16.000000  
29448  75.828002              27.100000  
29449  80.227910              67.000000  
29450  75.841749              27.800000  

[29451 rows x 12 columns]

In [32]:
x=dataset.iloc[:,[1,2,3,5,6,7]].values
x

array([[0.00000000e+00, 0.00000000e+00, 2.00000000e+00, 1.30023641e+03,
        1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, 1.27500000e+03,
        1.00000000e+00, 1.00000000e+00],
       [1.79762309e-01, 0.00000000e+00, 2.00000000e+00, 9.33159722e+02,
        1.00000000e+00, 1.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, 1.02264151e+03,
        1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, 9.27079009e+02,
        1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 2.00000000e+00, 8.96774194e+02,
        1.00000000e+00, 1.00000000e+00]])

In [33]:
y=dataset.iloc[:,-1].values
y

array([ 55.        ,  51.        , 142.91124597, ...,  27.1       ,
        67.        ,  27.8       ])

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [36]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()
l1.fit(x_train,y_train)

LinearRegression()

In [37]:
y_pred=l1.predict(x_test)
y_pred

array([ 67.01915124, 177.64275116, 149.37262539, ...,  67.07608657,
        67.05041598,  95.2978449 ])

In [38]:
x_test

array([[0.00000000e+00, 0.00000000e+00, 2.00000000e+00, 8.00000000e+02,
        1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 3.00000000e+00, 1.52434842e+03,
        1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.00000000e+00, 1.23583934e+03,
        1.00000000e+00, 1.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, 1.20988283e+03,
        1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.00000000e+00, 1.02507780e+03,
        1.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 2.00000000e+00, 1.15019011e+03,
        1.00000000e+00, 1.00000000e+00]])

In [39]:
y_test

array([20. , 88.9, 48. , ..., 95. , 56. , 48.4])