In [2]:
import numpy as np
import pandas as pd 

In [3]:
dataset=pd.read_csv("D:\Datasets\CarPrice.csv")
dataset

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [5]:
dataset.isnull().any()

car_ID              False
symboling           False
CarName             False
fueltype            False
aspiration          False
doornumber          False
carbody             False
drivewheel          False
enginelocation      False
wheelbase           False
carlength           False
carwidth            False
carheight           False
curbweight          False
enginetype          False
cylindernumber      False
enginesize          False
fuelsystem          False
boreratio           False
stroke              False
compressionratio    False
horsepower          False
peakrpm             False
citympg             False
highwaympg          False
price               False
dtype: bool

In [6]:
x=dataset.iloc[:,[9,10,11,12,13]].values
x

array([[  88.6,  168.8,   64.1,   48.8, 2548. ],
       [  88.6,  168.8,   64.1,   48.8, 2548. ],
       [  94.5,  171.2,   65.5,   52.4, 2823. ],
       ...,
       [ 109.1,  188.8,   68.9,   55.5, 3012. ],
       [ 109.1,  188.8,   68.9,   55.5, 3217. ],
       [ 109.1,  188.8,   68.9,   55.5, 3062. ]])

In [7]:
y=dataset.iloc[:,-1].values
y

array([13495.   , 16500.   , 16500.   , 13950.   , 17450.   , 15250.   ,
       17710.   , 18920.   , 23875.   , 17859.167, 16430.   , 16925.   ,
       20970.   , 21105.   , 24565.   , 30760.   , 41315.   , 36880.   ,
        5151.   ,  6295.   ,  6575.   ,  5572.   ,  6377.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8558.   ,  8921.   , 12964.   ,
        6479.   ,  6855.   ,  5399.   ,  6529.   ,  7129.   ,  7295.   ,
        7295.   ,  7895.   ,  9095.   ,  8845.   , 10295.   , 12945.   ,
       10345.   ,  6785.   ,  8916.5  ,  8916.5  , 11048.   , 32250.   ,
       35550.   , 36000.   ,  5195.   ,  6095.   ,  6795.   ,  6695.   ,
        7395.   , 10945.   , 11845.   , 13645.   , 15645.   ,  8845.   ,
        8495.   , 10595.   , 10245.   , 10795.   , 11245.   , 18280.   ,
       18344.   , 25552.   , 28248.   , 28176.   , 31600.   , 34184.   ,
       35056.   , 40960.   , 45400.   , 16503.   ,  5389.   ,  6189.   ,
        6669.   ,  7689.   ,  9959.   ,  8499.   , 

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.02,random_state=11)

In [9]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()
l1.fit(x_train,y_train)

LinearRegression()

In [10]:
y_pred=l1.predict(x_test)
y_pred

array([ 8668.38657811,  7634.06226426, 16918.32408921,  7139.33227497,
        3084.6783943 ,  7631.05676672, 14847.58775412, 24754.85179931,
        2426.5448596 , 10566.35752312, 18522.47525389,  6865.21726066,
        6492.33567293,  6888.95427992, 16804.38561881,  9240.46762915,
       18106.50230351, 12910.96908492,  6419.89628383,  3970.0228479 ,
        5923.51330129,  9451.2287174 ,  9230.97282145, 10491.03707095,
       15270.10669681, 14724.08163774,  8474.86800064,  7447.90447627,
        -965.17586998,  3246.60657686, 12771.05967019, 10135.31390311,
        7943.40056386,  2572.57513017,  2572.57513017,  3246.60657686,
       17454.97660786, 13456.78965032, 11245.23627373,  9565.29332011,
       15512.22429318,  3306.09474178, 14913.97779176, -4952.84851861,
       12416.43932279,  9619.78491821, 12759.58734471,  7634.06226426,
       12626.25488154,  7030.75833814, 10009.39197692,  8442.25772149,
        6218.33592798, 12573.10364986,  9280.32217879,  8606.67032805,
      

In [11]:
y_test

array([ 7349.   , 11845.   , 16515.   ,  6938.   ,  6377.   , 11048.   ,
       18620.   , 16695.   ,  7295.   , 11199.   , 22470.   ,  7395.   ,
        7299.   ,  6695.   , 24565.   ,  9279.   , 41315.   , 10595.   ,
        7799.   , 13495.   , 16500.   ,  7995.   ,  8189.   ,  7126.   ,
       15510.   , 15998.   , 11694.   ,  6692.   ,  6529.   , 32528.   ,
       13950.   , 12945.   , 12964.   ,  6692.   ,  7609.   , 34028.   ,
       15580.   , 13499.   ,  9639.   ,  9960.   , 15040.   ,  6795.   ,
       16558.   ,  6479.   , 10795.   , 10198.   , 16925.   , 10945.   ,
        9295.   ,  7198.   ,  8949.   , 10345.   ,  7898.   ,  8495.   ,
        9995.   ,  7999.   ,  6189.   ,  5348.   , 11595.   , 17859.167,
        9538.   ,  9989.   , 28176.   , 37028.   , 12290.   ,  5399.   ,
       30760.   , 40960.   , 15985.   ,  8449.   ,  7898.   , 18344.   ,
        8249.   ,  6095.   ,  9258.   ,  9298.   , 16630.   ,  7788.   ,
       14869.   ,  7609.   , 17199.   , 20970.   , 