In [59]:
import numpy as np
import pandas as pd

In [60]:
dataset=pd.read_csv("D:\Datasets\HousePrice.csv")
dataset

POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK    SQUARE_FT  \
0         Owner                 0.0     0        2       BHK  1300.236407   
1           NaN                 0.0     0        2       BHK  1275.000000   
2         Owner                 NaN     0        2       BHK   933.159722   
3           NaN                 0.0     1        2       BHK   929.921143   
4        Dealer                 1.0     0        2       BHK   999.009247   
...         ...                 ...   ...      ...       ...          ...   
29446     Owner                 0.0     0        3       BHK  2500.000000   
29447     Owner                 0.0     0        2       BHK   769.230769   
29448    Dealer                 0.0     0        2       BHK  1022.641509   
29449     Owner                 0.0     0        2       BHK   927.079009   
29450    Dealer                 0.0     1        2       BHK   896.774194   

       READY_TO_MOVE  RESALE                            ADDRESS  LONGITUDE  \
0                  1       1              Ksfc Layout,Bangalore  12.969910   
1                  1       1          Vishweshwara Nagar,Mysore  12.274538   
2                  1       1                   Jigani,Bangalore  12.778033   
3                  1       1        Sector-1 Vaishali,Ghaziabad  28.642300   
4                  0       1                   New Town,Kolkata  22.592200   
...              ...     ...                                ...        ...   
29446              1       1               Shamshabad Road,Agra  27.140626   
29447              1       1  E3-108, Lake View Recidency,,Vapi  39.945409   
29448              1       1                  Ajmer Road,Jaipur  26.928785   
29449              1       1             Sholinganallur,Chennai  12.900150   
29450              1       1                   Jagatpura,Jaipur  26.832353   

        LATITUDE  TARGET(PRICE_IN_LACS)  
0      77.597960                   55.0  
1      76.644605                   51.0  
2      77.632191                    NaN  
3      77.344500                   62.5  
4      88.484911                   60.5  
...          ...                    ...  
29446  78.043277                   45.0  
29447 -86.150721                   16.0  
29448  75.828002                   27.1  
29449  80.227910                   67.0  
29450  75.841749                   27.8  

[29451 rows x 12 columns]

In [64]:
data=dataset[["SQUARE_FT","TARGET(PRICE_IN_LACS)"]]
data

SQUARE_FT  TARGET(PRICE_IN_LACS)
0      1300.236407                   55.0
1      1275.000000                   51.0
2       933.159722                    NaN
3       929.921143                   62.5
4       999.009247                   60.5
...            ...                    ...
29446  2500.000000                   45.0
29447   769.230769                   16.0
29448  1022.641509                   27.1
29449   927.079009                   67.0
29450   896.774194                   27.8

[29451 rows x 2 columns]

In [66]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   SQUARE_FT              29451 non-null  float64
 1   TARGET(PRICE_IN_LACS)  29447 non-null  float64
dtypes: float64(2)
memory usage: 460.3 KB


In [67]:
data.isnull().any()

SQUARE_FT                False
TARGET(PRICE_IN_LACS)     True
dtype: bool

In [71]:
fn=data["TARGET(PRICE_IN_LACS)"].min()
fn

0.25

In [73]:
a=data["TARGET(PRICE_IN_LACS)"].fillna(fn,inplace=True)
a

In [74]:
data.isnull().any()

SQUARE_FT                False
TARGET(PRICE_IN_LACS)    False
dtype: bool

In [86]:
x=data.iloc[:,[0]].values
x

array([[1300.236407 ],
       [1275.       ],
       [ 933.1597222],
       ...,
       [1022.641509 ],
       [ 927.0790093],
       [ 896.7741935]])

In [87]:
y=data.iloc[:,[1]].values
y

array([[55.  ],
       [51.  ],
       [ 0.25],
       ...,
       [27.1 ],
       [67.  ],
       [27.8 ]])

In [88]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.02,random_state=11)

In [89]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()
l1.fit(x_train,y_train)

LinearRegression()

In [91]:
y_pred=l1.predict(x_test)
y_pred

array([[139.70021137],
       [139.4507104 ],
       [139.58592116],
       [139.58202856],
       [139.57085388],
       [139.5872361 ],
       [139.53350549],
       [139.79459445],
       [139.66330512],
       [139.4707896 ],
       [139.50970037],
       [139.51709924],
       [139.53197888],
       [139.47773699],
       [139.50136675],
       [139.63069657],
       [139.51612704],
       [139.55497111],
       [139.7071637 ],
       [139.54726379],
       [139.65074729],
       [139.6285913 ],
       [139.70023036],
       [139.56004043],
       [139.57343116],
       [139.57036472],
       [139.52042836],
       [139.68180846],
       [139.48377417],
       [139.60283144],
       [139.56483781],
       [139.56811721],
       [139.52795821],
       [139.58576541],
       [139.61795457],
       [139.52210918],
       [139.6237358 ],
       [139.53064248],
       [139.60148777],
       [139.62379932],
       [139.60289969],
       [139.52824912],
       [139.58204063],
       [139

In [93]:
y_test

array([[1.100e+02],
       [1.470e+01],
       [3.000e+02],
       [3.500e+02],
       [3.790e+01],
       [4.440e+01],
       [6.500e+01],
       [1.900e+02],
       [1.100e+02],
       [6.200e+01],
       [2.800e+01],
       [4.600e+01],
       [8.500e+01],
       [1.800e+01],
       [1.000e+02],
       [1.400e+02],
       [3.500e+01],
       [3.590e+01],
       [8.100e+01],
       [4.300e+01],
       [4.950e+01],
       [6.000e+01],
       [2.900e+02],
       [7.900e+01],
       [7.500e+01],
       [2.350e+01],
       [8.000e+01],
       [3.900e+02],
       [2.620e+01],
       [4.400e+01],
       [2.600e+02],
       [4.400e+01],
       [2.600e+01],
       [5.370e+01],
       [1.100e+02],
       [4.000e+01],
       [5.280e+01],
       [6.030e+01],
       [3.500e+01],
       [5.600e+01],
       [5.000e+01],
       [3.200e+01],
       [6.000e+01],
       [8.710e+01],
       [7.900e+01],
       [4.000e+01],
       [8.500e+01],
       [2.000e+02],
       [4.500e+02],
       [9.000e+01],


In [94]:
x_test

array([[2.20000000e+03],
       [4.05629139e+02],
       [1.37804318e+03],
       [1.35004822e+03],
       [1.26968174e+03],
       [1.38750000e+03],
       [1.00107808e+03],
       [2.87878788e+03],
       [1.93457615e+03],
       [5.50035486e+02],
       [8.29875519e+02],
       [8.83086965e+02],
       [9.90099010e+02],
       [6.00000000e+02],
       [7.69941484e+02],
       [1.70006072e+03],
       [8.76095119e+02],
       [1.15545542e+03],
       [2.25000000e+03],
       [1.10002558e+03],
       [1.84426229e+03],
       [1.68491997e+03],
       [2.20013656e+03],
       [1.19191310e+03],
       [1.28821711e+03],
       [1.26616379e+03],
       [9.07029478e+02],
       [2.06764924e+03],
       [6.43418468e+02],
       [1.49965917e+03],
       [1.22641509e+03],
       [1.25000000e+03],
       [9.61182994e+02],
       [1.37692308e+03],
       [1.60842228e+03],
       [9.19117647e+02],
       [1.65000000e+03],
       [9.80487805e+02],
       [1.48999574e+03],
       [1.65045682e+03],
