In [1]:
import numpy as np
import pandas as pd

In [3]:
dataset=pd.read_csv("D:\Datasets\AirQualityUCI.csv")
dataset

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0     10-03-2004  18:00:00     2.6       1360.0     150.0      11.9   
1     10-03-2004  19:00:00     2.0       1292.0     112.0       9.4   
2     10-03-2004  20:00:00     2.2       1402.0      88.0       9.0   
3     10-03-2004  21:00:00     2.2       1376.0      80.0       9.2   
4     10-03-2004  22:00:00     1.6       1272.0      51.0       6.5   
...          ...       ...     ...          ...       ...       ...   
9466         NaN       NaN     NaN          NaN       NaN       NaN   
9467         NaN       NaN     NaN          NaN       NaN       NaN   
9468         NaN       NaN     NaN          NaN       NaN       NaN   
9469         NaN       NaN     NaN          NaN       NaN       NaN   
9470         NaN       NaN     NaN          NaN       NaN       NaN   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0            1046.0    166.0        1056.0    113.0        1692.0   
1             955.0    103.0        1174.0     92.0        1559.0   
2             939.0    131.0        1140.0    114.0        1555.0   
3             948.0    172.0        1092.0    122.0        1584.0   
4             836.0    131.0        1205.0    116.0        1490.0   
...             ...      ...           ...      ...           ...   
9466            NaN      NaN           NaN      NaN           NaN   
9467            NaN      NaN           NaN      NaN           NaN   
9468            NaN      NaN           NaN      NaN           NaN   
9469            NaN      NaN           NaN      NaN           NaN   
9470            NaN      NaN           NaN      NaN           NaN   

      PT08.S5(O3)     T    RH      AH  Unnamed: 15  Unnamed: 16  
0          1268.0  13.6  48.9  0.7578          NaN          NaN  
1           972.0  13.3  47.7  0.7255          NaN          NaN  
2          1074.0  11.9  54.0  0.7502          NaN          NaN  
3          1203.0  11.0  60.0  0.7867          NaN          NaN  
4          1110.0  11.2  59.6  0.7888          NaN          NaN  
...           ...   ...   ...     ...          ...          ...  
9466          NaN   NaN   NaN     NaN          NaN          NaN  
9467          NaN   NaN   NaN     NaN          NaN          NaN  
9468          NaN   NaN   NaN     NaN          NaN          NaN  
9469          NaN   NaN   NaN     NaN          NaN          NaN  
9470          NaN   NaN   NaN     NaN          NaN          NaN  

[9471 rows x 17 columns]

In [5]:
data=dataset[["T","RH"]]
data

T    RH
0     13.6  48.9
1     13.3  47.7
2     11.9  54.0
3     11.0  60.0
4     11.2  59.6
...    ...   ...
9466   NaN   NaN
9467   NaN   NaN
9468   NaN   NaN
9469   NaN   NaN
9470   NaN   NaN

[9471 rows x 2 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   T       9357 non-null   float64
 1   RH      9357 non-null   float64
dtypes: float64(2)
memory usage: 148.1 KB


In [7]:
data.isnull().any()

T     True
RH    True
dtype: bool

In [9]:
fn=data["T"].max()
fn

44.6

In [12]:
a=data["T"].fillna(fn,inplace=True)
a

In [13]:
data.isnull().any()

T     False
RH     True
dtype: bool

In [14]:
fn=data["RH"].max()
fn

88.7

In [15]:
b=data["RH"].fillna(fn,inplace=True)
b

In [16]:
data.isnull().any()

T     False
RH    False
dtype: bool

In [19]:
x=data.iloc[0:500,[0]].values
x

array([[13.6],
       [13.3],
       [11.9],
       [11. ],
       [11.2],
       [11.2],
       [11.3],
       [10.7],
       [10.7],
       [10.3],
       [10.1],
       [11. ],
       [10.5],
       [10.2],
       [10.8],
       [10.5],
       [10.8],
       [10.5],
       [ 9.5],
       [ 8.3],
       [ 8. ],
       [ 8.3],
       [ 9.7],
       [ 9.8],
       [10.3],
       [ 9.7],
       [ 9.6],
       [ 9.1],
       [ 8.2],
       [ 8.2],
       [ 8.3],
       [ 7.7],
       [ 7.1],
       [ 7. ],
       [ 6.1],
       [ 6.3],
       [ 6.8],
       [ 6.4],
       [ 7.3],
       [ 9.2],
       [13.2],
       [14.3],
       [15. ],
       [16.1],
       [16.3],
       [15.8],
       [15.9],
       [16.9],
       [15.1],
       [14.4],
       [12.9],
       [12.1],
       [11. ],
       [ 9.7],
       [ 9.5],
       [ 9.1],
       [ 8.8],
       [ 7.8],
       [ 7. ],
       [ 8.3],
       [ 7.2],
       [ 6.3],
       [ 6.5],
       [ 9.6],
       [12.4],
       [15.6],
       [18

In [21]:
y=data.iloc[0:500,[-1]].values
y

array([[48.9],
       [47.7],
       [54. ],
       [60. ],
       [59.6],
       [59.2],
       [56.8],
       [60. ],
       [59.7],
       [60.2],
       [60.5],
       [56.2],
       [58.1],
       [59.6],
       [57.4],
       [60.6],
       [58.4],
       [57.9],
       [66.8],
       [76.4],
       [81.1],
       [79.8],
       [71.2],
       [67.6],
       [64.2],
       [69.3],
       [67.8],
       [64. ],
       [63.4],
       [60.8],
       [58.5],
       [59.7],
       [61.8],
       [62.3],
       [65.9],
       [65. ],
       [62.9],
       [65.1],
       [63.1],
       [56.2],
       [41.7],
       [38.4],
       [36.5],
       [34.5],
       [35.7],
       [37. ],
       [37.2],
       [34.3],
       [39.6],
       [43.4],
       [50.5],
       [53.3],
       [59.1],
       [64.6],
       [64.1],
       [63.9],
       [63.9],
       [67.5],
       [71.1],
       [63.6],
       [67.5],
       [71.9],
       [71.6],
       [59.7],
       [51.2],
       [42.2],
       [33

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [24]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()
l1.fit(x_train,y_train)

LinearRegression()

In [25]:
y_pred=l1.predict(x_test)
y_pred

array([[52.41993958],
       [41.2628682 ],
       [60.72287643],
       [56.31194123],
       [51.90100603],
       [63.57701097],
       [53.19833991],
       [55.79300768],
       [63.57701097],
       [57.86874189],
       [33.73833168],
       [59.16607577],
       [32.95993135],
       [54.4956738 ],
       [58.64714222],
       [56.57140801],
       [58.64714222],
       [57.34980834],
       [47.23060406],
       [49.30633827],
       [53.71727347],
       [43.85753596],
       [41.52233498],
       [44.11700274],
       [47.23060406],
       [38.14926688],
       [63.05807742],
       [65.13381163],
       [33.47886491],
       [66.95007906],
       [45.41433662],
       [45.41433662],
       [63.31754419],
       [33.99779846],
       [52.41993958],
       [39.44660076],
       [50.60367215],
       [52.16047281],
       [50.0847386 ],
       [51.1226057 ],
       [47.49007083],
       [60.98234321],
       [46.45220373],
       [57.60927511],
       [64.09594452],
       [51

In [26]:
y_test

array([[62.1],
       [38.4],
       [46.6],
       [45.6],
       [55.1],
       [62.2],
       [47.7],
       [46.8],
       [72.3],
       [58.2],
       [22.5],
       [61.4],
       [33.4],
       [63.2],
       [57. ],
       [69.7],
       [56.9],
       [38.7],
       [40.6],
       [52.1],
       [34.4],
       [46.1],
       [48.1],
       [35.3],
       [42.2],
       [42.6],
       [66.8],
       [74.6],
       [21.7],
       [81.1],
       [51. ],
       [47.1],
       [62.6],
       [31.1],
       [55.1],
       [36.2],
       [55.4],
       [49.5],
       [54.4],
       [49.8],
       [50.6],
       [64.2],
       [43.5],
       [62.2],
       [63.9],
       [33.2],
       [47.8],
       [66.8],
       [20.2],
       [40.4],
       [31.3],
       [49.7],
       [41.6],
       [53.1],
       [30.6],
       [40.1],
       [61.8],
       [31.3],
       [71. ],
       [62.2],
       [26.8],
       [60.6],
       [58. ],
       [26.1],
       [73.3],
       [59. ],
       [58